name: dev-to-sapper
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: peopledrivemecrazy/dev-to-sapper
  name: dev-to-sapper